coco/package.json, coco/public/index.html, coco/public/manifest.json, coco/src/App.js, coco/src/app/loginSlice.js, coco/src/app/store.js, coco/src/components/Home.jsx, coco/src/components/Login.jsx, coco/src/components/SignUp.css, coco/src/components/SignUp.jsx, coco/src/components/counter.jsx, coco/src/components/couterSlice.jsx, coco/src/index.js, main.py
: 회원가입 및 로그인 기닁 개발
-----------------------------------------DO----------------------------------------
1. fastapi로 post
2. mysql 연동
---------------------------------------TODO---------------------------------------
1. 리덕스로 로그인 유지
=> <feat> : 회원가입 및 로그인 개발

coco/src/components/Home/Home.css
<Feat> : Main UI
1. Notice Font 변경
=> <Feat> : Main UI

coco/package-lock.json, coco/src/App.js, coco/src/components/Home/Header.jsx, coco/src/components/Home/Home.jsx, coco/src/components/ProblemDetail/PBD.css, coco/src/components/ProblemDetail/PBD.jsx
: PBD UI
-------------------------------------DO------------------------------------
1. UI 틀 작성
2. input form txt 구현
------------------------------------TODO----------------------------------
1. route indexing
2. 반응형 UI
3. form 값 fastApi로 post
=> Feature {problem detail}

coco/src/App.js, coco/src/components/Home/Header.jsx, coco/src/components/Home/Home.css, coco/src/components/Login/SignUp.css, coco/src/components/ProblemDetail/PBD.css, coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Problems/Problems.css, coco/src/components/Problems/Problems.jsx
----------------------------------------
1. 문제 페이지 UI 수정
2. 문제 상세 페에지 라우팅 처리
----------------------------------------
1. 반응형 UI
=> <Feat> :  routing

coco/src/App.js, coco/src/components/Result/Result.css, coco/src/components/Result/Result.jsx
<Feat> : Result UI
-------------------DO----------------------
1. 결과창 UI 구성
2. 채점 결과에 따라 변화하는 UI 구성 
-----------------TODO---------------------
1. props로 code받아와서 띄우기
2. 정답 code랑 비교해서 표졍바꾸기
=> <Feat> : Result UI

coco/src/components/Home/Home.css, coco/src/components/Home/Home.jsx, coco/src/components/Manage/Manage.css, coco/src/components/Manage/Manage.jsx, coco/src/components/ProblemDetail/PBD.css
관리자 페이지 front 단 완성
1. Manage Page React to FastAPI
2. POST method complete
3. testCase Input made
1. Interactive UI
2. POST 시, FILE 에러 핸들링
=> <Feat> : Manage Front

coco/src/components/Home/Header.jsx, coco/src/components/Login/SignIn.jsx, coco/src/components/Login/SignUp.jsx
----------------------------------------
ex) : navigate 수정
1. useNavigate에서 window.location.href로 수정
=> <Feat> :  회원가입

coco/src/api/fetchTask.js, coco/src/api/wrapPromise.js, coco/src/components/Manage/Manage.jsx, coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Problems/Problems.jsx
: back-end와 통신
1. get method로 api 통신
2. suspense로 문제 페이지 구현
3. suspense로 상세 문제 페이지 구현
1. 코드 submit 처리
=> <Feat> :  api 통신

coco/src/components/Login/SignIn.jsx, coco/src/components/Login/SignUp.jsx
: 아이디 찾기 및 비밀번호 찾기
1. 이름, 이메일 입력으로 아이디 찾기
2. 이름, 이메일, 아이디 입력으로 pw 찾기
3. post method로 요청 
=> <Feat> :  로그인

coco/src/components/Board/All.jsx, coco/src/components/Board/Board.css, coco/src/components/Board/Board.jsx, coco/src/components/Board/BoardBox.jsx, coco/src/components/Board/BoardDetail/BD.css, coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Home/Header.jsx, coco/src/components/Login/SignUp.css
: 커뮤니티
1. 게시판 UI 수정
2. Board List Data 받아서 띄울 수 있게 수정
3. 좋아요, 댓글, 조회수 추가
1.게시판 내부 UI 수정
2.게시판 리스트에 좋아요 댓글 조회수 추가
=> <Feat> : Board

coco/src/App.js, coco/src/components/Board/Board.jsx, coco/src/components/Board/BoardBody.jsx, coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Board/FastWrite.jsx, coco/src/components/Board/WriteGeul/Free.jsx, coco/src/components/Board/WriteGeul/Help.jsx, coco/src/components/Board/WriteGeul/WriteGuel.css, coco/src/components/Board/WriteGeul/WriteGuel.jsx, coco/src/components/Home/Header.jsx, coco/src/components/Login/SignIn.jsx
: 게시판 상세 페이지 구현
1. axios와 get method로 api 호출
2. api 호출 비동기 처리
1. 좋아요 기능
2. 댓글 api 불러오기
=> Feat {board}

coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Result/Result.css, coco/src/components/Result/Result.jsx, coco/src/components/StatusList/StatusList.css, coco/src/components/StatusList/StatusList.jsx, coco/src/components/StatusList/StatusListBox.jsx
=> <Feat> :  코드 결과 보기

coco/package.json, coco/src/App.js, coco/src/app/authentication.js, coco/src/app/jwtdecode.js, coco/src/app/loginSlice.js, coco/src/app/store.js, coco/src/components/Auth/AuthRouter.jsx, coco/src/components/Board/BoardDetail/Comments/Comments.jsx, coco/src/components/Board/Guel.jsx, coco/src/components/Login/SignIn.jsx, coco/src/components/Manage/Manage.jsx, coco/src/components/Result/Result.jsx
=> Feature {인증}

coco/package.json, coco/src/App.js, coco/src/components/StatusList/StatusList.css, coco/src/components/StatusList/StatusList.jsx
Pagination
1. 채점상황 Pagination 구현
1. 문제 페이지 Pagination 구현
=> <Feat> :  페이징

coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Problems/Problems.jsx
1. 문제 정렬
1. 유형에 따른 문제 정렬
1. 반응형 디자인
=> <Feat> :  문제 정렬

coco/src/components/MyPage/MyPage.jsx, coco/src/components/MyPage/SecondBox.jsx
내가 푼 문제
1. 푼 문제 수 및 정답률
2. 맞은 문제 리스트 출력
3. 틀린 문제 리스트 출력
4. 월별 푼 문제 수 그래프 출력
5. 내 성장 그래프 출력
1. 반응형 디자인
=> <Feat> :  내가 푼 문제들

coco/src/components/Login/SignIn.jsx, coco/src/components/Login/SignUp.css
=> <Fix> :  자동로그인 체크박스 추가 - CO-30

coco/src/components/Home/Block.jsx, coco/src/components/Home/Footer.jsx, coco/src/components/Home/Header.jsx, coco/src/components/Home/Home.css, coco/src/components/Home/Home.jsx, coco/src/components/Login/Login.jsx, coco/src/components/Login/SignIn.jsx, coco/src/components/Login/SignUp.css, coco/src/components/Login/SignUp.jsx, coco/src/components/StatusList/StatusList.css
메인 화면에 그래프 추가
1. 메인화면 그래프 추가
2. 메인, 헤더 배치 변경
1. 반응형 디자인
=> Feat {main graph} co 89

coco/src/components/Home/Block.jsx, coco/src/components/Home/Home.jsx, coco/src/components/Problems/Problems.jsx, coco/src/components/StatusList/StatusList.jsx
문제 검색 및 채점 상황
1. 문제 페이지 문제 검색
2. 채점 상황 옵션별 정렬
3. 채점 상황 문제별
1. 반응형 디자인
=> <Feat> :  문제 검색 및 채점 상황

coco/src/App.js, coco/src/components/Auth/AuthRouter.jsx, coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Board/BoardDetail/Comments/Comments.jsx, coco/src/components/Board/WriteGeul/Help.jsx, coco/src/components/Board/WriteGeul/WriteGuel.css, coco/src/components/Board/WriteGeul/WriteGuel.jsx, coco/src/components/Manage/manageComponents/TaskUpload.jsx, coco/src/components/MyPage/ModifyBoard.jsx, coco/src/components/MyPage/MyPage.css, coco/src/components/MyPage/ThirdBox.jsx
게시판 추가 및 수정
1. 로그인 안했을 때 게시글 못보는 오류 해결
2. 내가 쓴 게시글 수정
3. 공지 게시판 및 help 게시판
4. 게시글 및 댓글 좋아요 오류 수정
5. 마이페이지 맞은 문제 번호 중복 삭제
1. 반응형 디자인
=> Feature {board}

coco/src/components/Home/DiffGraph.jsx, coco/src/components/Home/Home.jsx, coco/src/components/Home/HomeGraph.jsx
홈화면 그래프
1.  난이도별 학습률
2. 내 성장 그래프
1. 레벨 및 전체 등수
=> <Feat> :  홈화면 그래프

coco/src/components/Board/Board.css, coco/src/components/Board/Board.jsx, coco/src/components/Board/BoardBody.jsx, coco/src/components/Board/BoardDetail/BD.css, coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Board/FastWrite.jsx, coco/src/components/Board/Guel.css, coco/src/components/Board/Guel.jsx, coco/src/components/Board/WriteGeul/WriteGuel.css, coco/src/components/Board/WriteGeul/WriteGuel.jsx, coco/src/components/Home/Block.jsx, coco/src/components/Home/Footer.jsx, coco/src/components/Home/Header.jsx, coco/src/components/Home/Home.css, coco/src/components/Home/Home.jsx, coco/src/components/Loader/Loader.jsx, coco/src/components/Login/Login.jsx, coco/src/components/Login/SignUp.css, coco/src/components/Manage/Manage.css, coco/src/components/Manage/Manage.jsx, coco/src/components/MyPage/MyPage.css, coco/src/components/MyPage/MyPage.jsx, coco/src/components/MyPage/SecondBox.jsx, coco/src/components/Problems/Problems.css, coco/src/components/Problems/Problems.jsx, coco/src/components/StatusList/StatusList.css, coco/src/components/StatusList/StatusList.jsx
반응형 UI 완성
750px까지 반응형 UI 완성
핸드폰 접속용 -> flutter로 제작예정
=> Feat {responsive UI} co 90

coco/package.json, coco/src/components/MyPage/MyPage.jsx, coco/src/components/MyPage/MyTasks.jsx, coco/src/components/MyPage/SecondBox.jsx, coco/src/components/ProblemDetail/PBD.jsx
=> <Feat> :  내 문제집

coco/package-lock.json, coco/src/App.js, coco/src/components/Home/Header.jsx, coco/src/components/Home/Home.css, coco/src/components/MyPage/MyPage.css, coco/src/components/MyPage/MyTasks.jsx, coco/src/components/MyPage/SecondBox.jsx, coco/src/components/MyPage/ThirdBox.jsx, coco/src/components/ProblemDetail/PBD.css, coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Students/Students.jsx
내 문제집 추가
1. 과제 부여 버튼 추가
2. 마이페이지에서 내 문제집 확인가능
1. 내 문제 삭제기능
2. solve여부 api 추가
=> Feature {my tasks}

coco/src/components/Manage/manageComponents/TaskUpload.jsx
------------------------------------------------
1. 문제 메인 설명을 덱스트에디터로 수정
2. 텍스트 에디터 내에서 사진 입력 추가
ex) : 메인 UI 수정
ex) 1. Header 디자인 변경
ex) 1. 반응형 디자인
=> <Feat> : 문제 업로드 수정

coco/package.json, coco/src/components/Manage/manageComponents/Notice.jsx
------------------------------------------------
1. 공지사항 이미지 업로드
2. 공지사항 수정
ex) : 메인 UI 수정
ex) 1. Header 디자인 변경
ex) 1. 반응형 디자인
=> <Feat> : 공지 이미지 업로드 및 수정

coco/src/components/Group/AllGroupBox.jsx, coco/src/components/Group/GroupBox.jsx, coco/src/components/Group/GroupInfo.css, coco/src/components/Group/GroupInfo.jsx, coco/src/components/Home/Home.jsx
그룹 기능 추가
1. 그룹 관련 기능 추가
ex) 1. 반응형 디자인
=> Feature {group} co 91

coco/src/components/ProblemDetail/PBD.jsx
1. 그룹문제집에 문제 추가
1. 그룹문제집에 문제 추가
ex) 1. 반응형 디자인
=> <fix> : 그룹 문제집 #94

coco/src/components/Board/WriteGeul/Free.jsx, coco/src/components/Board/WriteGeul/WriteGuel.jsx
커뮤니티 글쓰기 오류 수정
1. 일반 사용자가 게시글 작성시 카테고리에 공지 메뉴가 있는 오류 수정
2. 게시글 UI가 카테고리에 따라 바뀌게 수정
ex) 1. 반응형 디자인
=> <fix> : 커뮤니티 글쓰기 #89, #92

coco/src/components/Board/Board.jsx, coco/src/components/Board/FastWrite.jsx
커뮤니티 글쓰기 오류 수정
1. 로그인하지 않은 사용자가 글쓰기를 할 때의 오류 수정
ex) 1. 반응형 디자인
=> <fix> : 커뮤니티 글쓰기 #93

coco/src/components/Group/MakeGroup.css, coco/src/components/Group/MakeGroup.jsx
그룹 이슈 수정
1. 그룹명, 그룹설명 미 작성 시 그룹 생성 안되게
2. 설명문 변경
ex) 1. 반응형 디자인
=> <fix> : 그룹#100

coco/package.json, coco/src/components/MyPage/FirstBox.jsx, coco/src/components/MyPage/MyPage.css, coco/src/components/ProblemDetail/PBD.jsx
마이페이지 UI 수정
ex) 1. Header 디자인 변경
ex) 1. 반응형 디자인
=> <fix> - 마이페이지

coco/package-lock.json, coco/src/components/Board/WriteGeul/Help.jsx, coco/src/components/Board/WriteGeul/WriteGuel.css, coco/src/components/Group/GroupInfo.jsx, coco/src/components/Group/QA/QA.css, coco/src/components/Group/QA/QA.jsx, coco/src/components/Group/RoadMap/MakeRoadMap.jsx, coco/src/components/Group/RoadMap/RoadMap.jsx
Q&A UI/UX 제작
Q&A UI/UX 제작
1. API 연동
=> Feature {qa UI} co 119

coco/src/components/Group/GroupInfo.jsx, coco/src/components/Group/RoadMap/RoadMap.css, coco/src/components/Group/RoadMap/RoadMap.jsx
RoadMap
1. RoadMap 리스트 UI
ex) 1. 반응형 디자인
=> <Feat> : RoadMap

coco/src/App.js, coco/src/components/Board/Board.jsx, coco/src/components/Board/BoardBody.jsx, coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Board/BoardDetail/Comments/Comments.jsx, coco/src/components/Board/BoardDetail/Comments/WriteComment.jsx, coco/src/components/Board/FastWrite.jsx, coco/src/components/Board/Guel.jsx, coco/src/components/Board/WriteGeul/Free.jsx, coco/src/components/Board/WriteGeul/Help.jsx, coco/src/components/Manage/manageComponents/PostList.jsx
커뮤니티 리팩토링
1. 백엔드 api 수정에 맞게 수정
=> <Refactor> : 커뮤니티 리팩토링

coco/package.json, coco/src/App.js, coco/src/components/Manage/Manage.css, coco/src/components/Manage/Manage.jsx, coco/src/components/Manage/manageComponents/TaskList.jsx, coco/src/components/Manage/manageComponents/TaskModify.jsx, coco/src/components/Manage/manageComponents/TaskUpload.jsx, coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Problems/Problems.css, coco/src/components/Problems/Problems.jsx
task 관련 리팩토링 및 기능 구현
1. task 관련 리팩토링
2. task 페이지네이션
3. 매니저 페이지 문제 수정 구현
=> task 관련 리팩토링 및 기능 구현

coco/src/components/Group/GroupInfo.jsx, coco/src/components/MyPage/FirstBox.jsx, coco/src/components/MyPage/MyPage.jsx, coco/src/components/MyPage/SecondBox.jsx
마이페이지 분리
1. 남이 봤을 때 랑 내가 봤을때 마이페이지 분리
1. 디자인 수정, 현재 다른사람 페이지에서 내 페이지로 이동
=> Feature {mypage분리} co 121

coco/Dockerfile
프론트엔트 도커파일 작성
1. 프론트엔트 도커파일 작성
ex) 1. 반응형 디자인
=> <Feat> :  도커

coco/package-lock.json, coco/src/App.js, coco/src/components/Group/GroupInfo.jsx, coco/src/components/Group/RoadMap/Inside.css, coco/src/components/Group/RoadMap/Inside.jsx, coco/src/components/Group/RoadMap/MakeRoadMap.css, coco/src/components/Group/RoadMap/MakeRoadMap.jsx, coco/src/components/Group/RoadMap/RoadMap.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Problems/Problems.css, coco/src/components/Problems/Problems.jsx
로드맵 기능 진행중
1. 로드맵 생성 기능 구현
2. 로드맵 상세 정보 구현
1. 로드맵 삭제 기능 API 오류
2. 로드맵 수정 기능 구현
=> Feat {roadmap} co 115

coco/src/App.js, coco/src/components/Group/AllGroupBox.jsx, coco/src/components/Group/Group.jsx, coco/src/components/Group/QA/QA.jsx, coco/src/components/Group/Tutor/Tutor.css, coco/src/components/Group/Tutor/Tutor.jsx, coco/src/components/Manage/Manage.css, coco/src/components/Manage/Manage.jsx, coco/src/components/Manage/manageComponents/TutorApp.jsx, coco/src/components/Manage/manageComponents/User.jsx, coco/src/components/Result/Result.css, coco/src/components/Result/Result.jsx
튜터 신청란추가, 채점 결과 UI 수정
1. 튜터 신청란추가, 채점 결과 UI 수정
2. 관리자가 튜터 신청한 사람들 확인 가능
1. 채점 결과 페이지 디테일 추가
=> Feature {tutor req} co 135

coco/src/components/Result/Result.css, coco/src/components/Result/Result.jsx
pylint 채점 결과 보여주는 창 추가
1. UI틀 있음
=> feat : 채점 UI

coco/src/components/Group/QA/QA.css, coco/src/components/Group/QA/QA.jsx, coco/src/components/Result/Result.css, coco/src/components/Result/Result.jsx
WPC 창 생성
그룹 QA 채택 기능 생성
1. WPC 창 생성
2. 그룹 QA 채택 기능 생성
1. 코드 비교
2. 코드 밑줄 기능 수정
3. 코드 들여쓰기 생각
=> <feat> : WPC 창 생성

coco/src/api/config.js, coco/src/components/Group/QA/QA.jsx
답변 채택
1. 질문에 대한 답변 채택 api 호출
ex) 1. 반응형 디자인
=> <Feat> :  답변 채택

coco/src/components/Group/QA/QA.jsx
QA 오류 수정
1. 질문 작성자가 질문에 대한 답변을 채택 못하는 오류 수정
ex) 1. 반응형 디자인
=> <fix> : 질문 답변 오류 수정

coco/src/api/config.js, coco/src/components/Alarm/Alarm.jsx, coco/src/components/Group/QA/QA.jsx
알람 API
1. 질문 채택 시 질문 작성자 , 답변 작성자 넘기기
1. 알람 api 호출 필요
=> <Feat> :  알람

coco/src/components/MyPage/FirstBox.jsx, coco/src/components/MyPage/MyPage.css
남이 내꺼 봤을 때 마이페이지 UI 변경
1. 남이 내꺼 봤을 때 마이페이지 UI 변경
=> feat : mypage

coco/src/app/loginSlice.js, coco/src/components/Alarm/Alarm.jsx, coco/src/components/Home/Header.jsx, coco/src/components/Login/SignIn.jsx
알람 확인
1. 안읽은 알람 있으면 로그인 사진 변경
2. 알람 확인 api
ex) 1. 반응형 디자인
=> <Feat> : 알람

coco/src/components/Board/BoardDetail/BD.css, coco/src/components/Board/WriteGeul/WriteGuel.css, coco/src/components/Group/QA/QA.css, coco/src/components/ProblemDetail/PBD.css, coco/src/components/Result/Result.jsx
오류 fix 짧은 Sprint
1. 코드 틀린거 보여주는 부분 Title 추가
2. 채졈결과 상세보기 문제 Detail 정보 오류 해결
3. selection Color 안보이는 문제 해결
1. 스터디룸 Q 등록된 코드 보여주는 부분 디자인 수정 -> Code Mirror 빼도 될듯
=> Feature {short sprint minsu}

coco/src/api/config.js, coco/src/components/Group/MakeGroup.jsx, coco/src/components/Home/Home.jsx, coco/src/components/MyPage/FirstBox.jsx
레벨 api
1. 유저 레벨 api 호출
ex) 1. 반응형 디자인
=> <Feat> :  레벨

coco/src/components/Group/QA/QA.css, coco/src/components/Group/QA/QA.jsx, coco/src/components/Home/Block.jsx, coco/src/components/Home/Home.css, coco/src/components/Home/Home.jsx, coco/src/components/Problems/Problems.css, coco/src/components/Problems/Problems.jsx, coco/src/components/StatusList/StatusList.jsx
11차 스프린트 완
1. 문제 리스트 정렬 반응형
2. Hot 배너 UI 변경
3. QA 코드 UI 변경
=> Feature {11st sprint} co 168 11

coco/src/components/Board/BoardDetail/BoardDetail.jsx, coco/src/components/Board/WriteGeul/Free.jsx, coco/src/components/Board/WriteGeul/Help.jsx, coco/src/components/Group/BoardWrite/WriteHelp.jsx, coco/src/components/Group/GroupInfo.jsx, coco/src/components/Group/MakeGroup.jsx, coco/src/components/Group/QA/QA.jsx, coco/src/components/Group/RoadMap/Inside.jsx, coco/src/components/Group/RoadMap/MakeRoadMap.jsx, coco/src/components/Group/RoadMap/ModifyRoadMap.jsx, coco/src/components/Group/Tutor/Tutor.jsx, coco/src/components/Manage/manageComponents/Notice.jsx, coco/src/components/Manage/manageComponents/PostList.jsx, coco/src/components/Manage/manageComponents/TaskList.jsx, coco/src/components/Manage/manageComponents/TutorApp.jsx, coco/src/components/Manage/manageComponents/User.jsx, coco/src/components/ProblemDetail/PBD.jsx, coco/src/components/Problems/ProblemBox.jsx, coco/src/components/Result/Result.jsx
1. Alert to Swal
2. 개선된 코드보기 인터페이스 완료
3. Plugin기능 인터페이스 완료
=> <feat> : 기능 변경 및 수정

coco/src/components/Manage/manageComponents/AITask.jsx, coco/src/components/MyPage/ModifyBoard.jsx, coco/src/components/MyPage/SecondBox.jsx, coco/src/components/MyPage/ThirdBox.jsx
----------------------------------------
1. 내 게시글 수정
2. ai 문제 생성 오류 수정
----------------------------------------
1. 앞으로 할 일
=> <Feat> :  내 게시글 수정
